stages:
  - build
  - test

image: docker:24.0.5

services:
  - name: docker:24.0.5-dind
    command: ["--tls=false"]

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_REPOSITORY: $CI_REGISTRY_IMAGE
  TEST_PORT: "8080"

before_script:
  - apk add --no-cache curl
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build_image:
  stage: build
  script:
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - IMAGE_WITH_TAG="$IMAGE_REPOSITORY:$RELEASE_TAG"
    - echo "Bygger $IMAGE_WITH_TAG"
    - docker build -t "$IMAGE_WITH_TAG" -t "$IMAGE_REPOSITORY:latest" .
    - docker push "$IMAGE_WITH_TAG"
    - docker push "$IMAGE_REPOSITORY:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

test_container:
  stage: test
  needs: ["build_image"]
  script:
    - RELEASE_TAG="LOv$CI_PIPELINE_IID"
    - IMAGE_WITH_TAG="$IMAGE_REPOSITORY:$RELEASE_TAG"
    - docker pull "$IMAGE_WITH_TAG"
    - docker rm -f test-$CI_JOB_ID || true
    - docker run -d -p "$TEST_PORT:80" --name test-$CI_JOB_ID "$IMAGE_WITH_TAG"
    - sleep 5
    - curl -f "http://localhost:$TEST_PORT/" || (echo "App did not respond"; docker logs test-$CI_JOB_ID; exit 1)
    - docker rm -f test-$CI_JOB_ID || true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
