stages:
  - debug

debug_webserver2:
  stage: debug
  script:
    - echo "DEBUG: Starter debug_webserver2-jobb"
    - echo "DEBUG: CI_PROJECT_PATH = $CI_PROJECT_PATH"
    - echo "DEBUG: CI_COMMIT_REF_NAME = $CI_COMMIT_REF_NAME"
    - echo "DEBUG: Runner host: $(hostname)"
    - echo "DEBUG: Nåværende katalog: $(pwd)"
    - echo "DEBUG: Innhold i repo-katalog:"
    - ls -R

    - echo "DEBUG: Sjekker om apk finnes:"
    - which apk || echo "apk finnes ikke på runner (forventet på shell-runner)"

    - echo "DEBUG: Sjekker om curl finnes:"
    - which curl || echo "curl ikke funnet i PATH"

    - echo "DEBUG: Sjekker om docker finnes:"
    - which docker || echo "docker ikke funnet i PATH"
    - docker version || echo "docker kommando feilet, sjekk docker-install på runner"

    - echo "DEBUG: Ferdig debug_webserver2-jobb"
